/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_term_useopencvwithndk_build_MainActivity */

#ifndef _Included_com_term_useopencvwithndk_build_MainActivity
#define _Included_com_term_useopencvwithndk_build_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_term_useopencvwithndk_build_MainActivity_PERMISSIONS_REQUEST_CODE
#define com_term_useopencvwithndk_build_MainActivity_PERMISSIONS_REQUEST_CODE 1000L
/*
 * Class:     com_term_useopencvwithndk_build_MainActivity
 * Method:    ConvertRGBtoGray
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_term_useopencvwithndk_1build_MainActivity_ConvertRGBtoGray
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
